require("prototypes/make-all-mu-types")
require("prototypes/FactorioExtended-Plus-Transport")
require("prototypes/FactorioExtended-Trains")
require("prototypes/BatteryPack")
require("prototypes/Krastorio2")
